version: "3.8"
services: 
    web:
        container_name: web
        build: .
        ports: 
            - 8080:8080
        depends_on: 
            - redis
    redis:
        container_name: redis
        image: redis:alpine
